server.port: 8888
spring.application.name: config-server

spring.profiles.active: native
spring.cloud.config.server.native.searchLocations: file:/home/nicola/IdeaProjects/learn-microservices/modules/infrastructure/code/centralized-configuration/config-repo
encrypt.key: ${CONFIG_SERVER_ENCRYPT_KEY}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
spring.config.activate.on-profile: docker
eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
spring.cloud.config.server.native.searchLocations: file:/config-repo