server.port: 8888
spring.application.name: config-server

spring.security.user:
  name: ${CONFIG_SERVER_USR}
  password: ${CONFIG_SERVER_PWD}

spring.profiles.active: native
spring.cloud.config.server.native.searchLocations: file:/home/nicolab/IdeaProjects/learn-microservices/code/spring-cloud-config-end/config-repo
encrypt.key: ${CONFIG_SERVER_ENCRYPT_KEY}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: info

---
spring.config.activate.on-profile: docker
eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/
spring.cloud.config.server.native.searchLocations: file:/config-repo