services:
  eureka:
    build: eureka-service
    mem_limit: 512m
    ports:
      - "8761:8761"

  nginx:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - datetime

  datetime:
    build: datetime-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      mode: replicated
      replicas: 3
