server.port: 8081

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: messages-group
      auto-offset-reset: earliest
    producer:
      acks: all


spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings:
    message-out-0:
      destination: messages