server.port: 8082

spring.cloud.stream:
  function:
    definition: requestReceiver
  bindings:
    message-out-0:
      contentType: application/json
      destination: queue.response
      binder: local_rabbit
    requestReceiver-in-0:
      contentType: application/json
      destination: queue.request
      binder: local_rabbit
  binders:
    local_rabbit:
      type: rabbit
      environment:
        spring:
          rabbitmq:
            host: 127.0.0.1
            port: 5672
            username: guest
            password: guest

---
spring.config.activate.on-profile: docker
spring.cloud.stream:
  binders:
    local_rabbit:
      environment:
        spring:
          rabbitmq:
            host: lavinmq
