apiVersion: apps/v1
kind: Deployment
metadata:
  name: composite-service-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composite-service-end
  template:
    metadata:
      labels:
        app: composite-service-end
    spec:
      containers:
        - name: composite-service-end
          image: composite:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
