apiVersion: v1
kind: Service
metadata:
  name: composite-service-end
spec:
  type: NodePort
  selector:
    app: composite-service-end
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
