services:
  product-service:
    image: product-service-no-db
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  order-service:
    build: order-service-no-db
    image: order-service-no-db
    mem_limit: 512m
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=docker
