server.port: 8080
spring.application.name: gateway-service
app.eureka-server: localhost
app.prometheus-server: localhost
app.grafana-server: localhost

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

spring.cloud.gateway.routes:
  - id: composite-service
    uri: lb://composite-service
    predicates:
      - Path=/time/**
  - id: eureka-web-start
    uri: http://${app.eureka-server}:8761
    predicates:
      - Path=/eureka/web
    filters:
      - SetPath=/
  - id: eureka-web-other
    uri: http://${app.eureka-server}:8761
    predicates:
      - Path=/eureka/**
  - id: grafana
    uri: http://${app.grafana-server}:3000
    predicates:
      - Path=/grafana/**
    filters:
      - RewritePath=/grafana/(?<remaining>.+), /$\{remaining}
  - id: prometheus
    uri: http://${app.prometheus-server}:9090
    predicates:
      - Path=/prometheus/**
    filters:
      - RewritePath=/prometheus/(?<remaining>.+), /$\{remaining}

---
spring.config.activate.on-profile: docker
server.port: 8080
app.eureka-server: eureka
app.prometheus-server: prometheus
app.grafana-server: grafana
